[phases.setup]
nixPkgs = ["python311Full"]

[phases.install]
cmds = ["curl -LsSf https://astral.sh/uv/install.sh | sh", "export PATH=\"$HOME/.local/bin:$PATH\"", "uv sync"]

[start]
cmd = "cd src && python run_service.py"
